<a href="https://colab.research.google.com/github/ahsanuamal/ahsanuamal/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import numpy
import numpy as np
from numpy import genfromtxt

In [3]:
#membaca data dari file
Xole = genfromtxt('/tmp/6.3_HalticaOleracea.csv', delimiter=',')
Xcar = genfromtxt('/tmp/6.3_HalticaCarduorum.csv', delimiter=',')

In [4]:
#hitung matrik kovarians kelas 1 (Haltica oleracea)
#dan kelas 2 (Haltica carduorum)
XoleCentered = Xole - Xole.mean(axis=0)
XcarCentered = Xcar - Xcar.mean(axis=0)
Sole = np.dot(XoleCentered.T, XoleCentered) / (Xole.shape[0] - 1)
Scar = np.dot(XcarCentered.T, XcarCentered) / (Xcar.shape[0] - 1)
print("Sole: ", Sole)
print("Scar: ", Scar)

Sole:  [[187.59649123 176.8625731   48.37134503 113.58187135]
 [176.8625731  345.38596491  75.97953216 118.78070175]
 [ 48.37134503  75.97953216  66.35672515  16.24269006]
 [113.58187135 118.78070175  16.24269006 239.94152047]]
Scar:  [[101.83947368 128.06315789  36.98947368  32.59210526]
 [128.06315789 389.01052632 165.35789474  94.36842105]
 [ 36.98947368 165.35789474 167.53684211  66.52631579]
 [ 32.59210526  94.36842105  66.52631579 177.88157895]]


In [5]:
#hitung matrik kovarians S (gabungan)
S = ((Xole.shape[0] - 1) * Sole + (Xcar.shape[0] - 1) * Scar)\
    / ((Xole.shape[0] - 1) + (Xcar.shape[0] - 1))
print("S: ", S)

S:  [[143.55910384 151.80341394  42.52660028  71.99253201]
 [151.80341394 367.78776671 121.87652916 106.24466572]
 [ 42.52660028 121.87652916 118.3140825   42.06401138]
 [ 71.99253201 106.24466572  42.06401138 208.07290185]]


In [6]:
#hitung matrik projeksi a (koefisien LDA)
meanXol = Xole.mean(axis=0); meanXol=np.asmatrix(meanXol).T
meanXcar = Xcar.mean(axis=0); meanXcar=np.asmatrix(meanXcar).T
a = np.dot(np.linalg.inv(S), np.subtract(meanXol, meanXcar))
a = np.asmatrix(a)

In [7]:
#hitung treshold
thresh = 0.5 * np.dot((np.add(meanXol, meanXcar)).T, a)
print("matriks proyeksi a: ", a)
print("konstanta treshold: ", thresh)

matriks proyeksi a:  [[ 0.34524895]
 [-0.13038778]
 [-0.1064338 ]
 [-0.14335331]]
konstanta treshold:  [[-15.80538483]]


In [8]:
#proyeksikan data dengan matriks proyeksi a
XoleLDA = np.dot(Xole,a)
XcarLDA = np.dot(Xcar,a)
print("Haltica Oleracea setelah LDA: ", XoleLDA)
print("Haltica Carduorum setelah LDA: ", XcarLDA)

Haltica Oleracea setelah LDA:  [[ -4.64097487]
 [-12.76995437]
 [ -3.59900662]
 [ -8.33378308]
 [ -8.39845855]
 [ -8.31969141]
 [ -5.99878876]
 [ -7.1049744 ]
 [-14.26965888]
 [ -8.795039  ]
 [ -5.37765953]
 [ -6.68555568]
 [ -7.53140232]
 [-11.53346371]
 [-10.92250425]
 [-11.16822278]
 [ -7.64662255]
 [-12.53181468]
 [-14.52461586]]
Haltica Carduorum setelah LDA:  [[-26.82287426]
 [-17.4586876 ]
 [-26.37315284]
 [-24.33482433]
 [-25.69496179]
 [-26.66657268]
 [-27.4867502 ]
 [-15.04791228]
 [-21.36303743]
 [-23.60089772]
 [-28.77137721]
 [-22.02204185]
 [-20.07453014]
 [-26.9941045 ]
 [-21.10153825]
 [-23.62355843]
 [-16.05087606]
 [-23.30440709]
 [-17.34108987]
 [-18.97462902]]


In [10]:
#terapkan threshold untuk pemisahan kelas
XoleLDA_prediksi = np.full((XoleLDA.shape),0)
XoleLDA_prediksi[XoleLDA>thresh]=1#jika lbh dari thresh, masuk ke kelas 1
XoleLDA_prediksi[XoleLDA<=thresh]=2#jika krg dari atw sama, masuk ke kelas 2
XcarLDA_prediksi = np.full((XcarLDA.shape),0)
XcarLDA_prediksi[XcarLDA>thresh]=1#jika lbh dari thresh, masuk ke kelas 1
XcarLDA_prediksi[XcarLDA<=thresh]=2#jika krg dari/sama, masuk ke kelas 2
print("XoleLDA_prediksi:", "\n", XoleLDA_prediksi)
print("XcarLDA_prediksi:", "\n", XcarLDA_prediksi)

XoleLDA_prediksi: 
 [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
XcarLDA_prediksi: 
 [[2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]
