<a href="https://colab.research.google.com/github/ahsanuamal/ahsanuamal/blob/main/Transformasi_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# import numpy
import numpy as np

In [8]:
# mendefinisikan matriks x secara bebas, untuk contoh saja
x = np.matrix([[-20,23,5],[4,-8,15]])

In [9]:
# centering (data asli dikurangi nilai rata-rata)
x_centering = x - x.mean()
print("x_centering:", x_centering, "\n")

x_centering: [[-23.16666667  19.83333333   1.83333333]
 [  0.83333333 -11.16666667  11.83333333]] 



In [11]:
# standarisasi
x_standarisasi = (x-x.mean())/x.std()
print("x_standarisasi: ", x_standarisasi)
print("mean x_standarisasi: ", x_standarisasi.mean())
print("varian x_standarisasi: ", x_standarisasi.var(), "\n")

x_standarisasi:  [[-1.6389276   1.40311068  0.12969931]
 [ 0.05895423 -0.78998669  0.83715007]]
mean x_standarisasi:  -1.850371707708594e-17
varian x_standarisasi:  1.0000000000000002 



In [14]:
# scaling ke range 0-1
BA = 1; BB = 0 # BA = batas atas, BB = batas bawah
x_scaling = (x - x.min()) / (x.max()-x.min()) * (BA-BB) + BB
print("x_scaling: ", x_scaling)

x_scaling:  [[0.         1.         0.58139535]
 [0.55813953 0.27906977 0.81395349]]
